apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: node
        image: ajay4uu/nodeapp
        ports:
        - containerPort: 4000
        imagePullPolicy: Never
        env:
          - name: MONGO_URL
            value: mongodb://mongo:27017/todo