apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
  name: example
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 32001
  selector:
    app: example
  type: NodePort
status:
  loadBalancer: {}